name: suwayomi
services:
  suwayomi:
    container_name: suwayomi
    image: ghcr.io/suwayomi/tachidesk:latest
    restart: unless-stopped
    network_mode: bridge
    hostname: suwayomi
    environment:
      BIND_IP: 0.0.0.0
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - target: 4567
        published: "4567"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/suwayomi
        target: /home/suwayomi/.local/share/Tachidesk
