name: suwayomi
services:
  suwayomi:
    container_name: suwayomi
    image: ghcr.io/suwayomi/tachidesk:latest
    restart: unless-stopped
    network_mode: bridge
    hostname: suwayomi
    environment:
      BIND_IP: 0.0.0.0
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 4567:4567/tcp
    volumes:
      - /DATA/AppData/suwayomi:/home/suwayomi/.local/share/Tachidesk
