name: homepage
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.5.201:3000,homepage.local,homepage.lucarotto-local.duckdns.org,homepage.lucarotto.duckdns.org
      # PGID: "1000" # Root permission needed to access Docker socket
      # PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 3000:3000/tcp
    volumes:
      - /DATA/AppData/homepage/config:/app/config
      - /DATA/AppData/homepage/icons:/app/public/icons
      - /DATA/AppData/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
