name: nginxproxymanager
services:
  nginxproxymanager-local:
    container_name: nginxproxymanager-local
    image: jc21/nginx-proxy-manager:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: nginxproxymanager-local
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports:
      - 80:80/tcp
      - 80:80/udp
      - 443:443/tcp
      - 443:443/udp
      - 1181:81/tcp
    volumes:
      - /DATA/AppData/nginxproxymanager-local/data:/data
      - /DATA/AppData/nginxproxymanager-local/letsencrypt:/etc/letsencrypt

  nginxproxymanager-remote:
    container_name: nginxproxymanager-remote
    image: jc21/nginx-proxy-manager:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: nginxproxymanager-remote
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports:
      - 2280:80/tcp
      - 2280:80/udp
      - 2443:443/tcp
      - 2443:443/udp
      - 2281:81/tcp
    volumes:
      - /DATA/AppData/nginxproxymanager-remote/data:/data
      - /DATA/AppData/nginxproxymanager-remote/letsencrypt:/etc/letsencrypt
