name: vaultwarden
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    hostname: vaultwarden
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.vaultwarden.loadbalancer.server.port: "80"

      traefik.http.routers.vaultwarden-duckdns-local.rule: Host(`vaultwarden.lucarotto-local.duckdns.org`)
      traefik.http.routers.vaultwarden-duckdns-local.entrypoints: https
      traefik.http.routers.vaultwarden-duckdns-local.tls: true
      traefik.http.routers.vaultwarden-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.vaultwarden-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.vaultwarden-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.vaultwarden-local.rule: Host(`vaultwarden.l.lucarotto.it`)
      traefik.http.routers.vaultwarden-local.entrypoints: http

      traefik.http.routers.vaultwarden-internet.rule: Host(`password.lucarotto.it`)
      traefik.http.routers.vaultwarden-internet.entrypoints: https-internet
      traefik.http.routers.vaultwarden-internet.tls: true
      traefik.http.routers.vaultwarden-internet.tls.certresolver: lucarotto-http
      traefik.http.routers.vaultwarden-internet.tls.domains[0].main: lucarotto.it
      traefik.http.routers.vaultwarden-internet.tls.domains[0].sans: "*.lucarotto.it"
    environment:
      DOMAIN: https://vaultwarden.lucarotto-local.duckdns.org
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /DATA/AppData/vaultwarden:/data
    ports: []
      # Disabled in favor of Traefik routing
      # - 8022:80
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false

networks:
  traefik:
    external: true
