name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: jellyfin
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 7359:7359/tcp
      - 1900:1900/tcp
    volumes:
      - /DATA/AppData/jellyfin/config:/config
      - /DATA:/DATA
      - /opt/vc/lib:/opt/vc/lib
      - /media:/media:rslave
      - /mnt:/mnt:rslave
    # devices:
      # - /dev/dri:/dev/dri
      # - /dev/vcsm:/dev/vcsm
      # - /dev/vchiq:/dev/vchiq
      # - /dev/video10:/dev/video10
      # - /dev/video11:/dev/video11
      # - /dev/video12:/dev/video12
