name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    hostname: jellyfin
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
      traefik.udp.services.jellyfin-zeroconf.loadbalancer.server.port: "7359"

      traefik.http.routers.jellyfin-duckdns-local.rule: Host(`jellyfin.lucarotto-local.duckdns.org`)
      traefik.http.routers.jellyfin-duckdns-local.entrypoints: https
      traefik.http.routers.jellyfin-duckdns-local.tls: true
      traefik.http.routers.jellyfin-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.jellyfin-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.jellyfin-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.jellyfin-local.rule: Host(`jellyfin.l.lucarotto.it`)
      traefik.http.routers.jellyfin-local.entrypoints: http

      traefik.udp.routers.jellyfin-zeroconf.service: jellyfin-zeroconf
      traefik.udp.routers.jellyfin-zeroconf.entryPoints: jellyfin-zeroconf
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8096:8096/tcp # HTTP
      - 8920:8920/tcp # HTTPS
      - 7359:7359/udp # Zeroconf
    volumes:
      - /DATA/AppData/jellyfin/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /DATA:/DATA
      - /opt/vc/lib:/opt/vc/lib
      - /media:/media:rslave
      - /mnt:/mnt:rslave
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"   # Your video GID
      - "993"  # Your render GID
    dns:
      - 172.18.0.100

networks:
  traefik:
    external: true
