name: servarr
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    hostname: gluetun
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.2
    environment:
      VPN_SERVICE_PROVIDER: surfshark
      VPN_TYPE: wireguard
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8083:8083 # qbittorrent web interface
      # - 6881:6881 # qbittorrent torrent port
      - 6789:6789 # nzbget
      - 9696:9696 # prowlarr
      - 8191:8191 # flaresolverr
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 8686:8686 # lidarr
      - 6767:6767 # bazarr
      - 8090:8090 # mylar
      - 8787:8787 # readarr
    volumes:
      - /DATA/AppData/servarr/gluetun:/gluetun
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:gluetun
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      WEBUI_PORT: 8083 # must match "qbittorrent web interface" port number in gluetun's service above
      # TORRENTING_PORT: ${FIREWALL_VPN_INPUT_PORTS} # airvpn forwarded port, pulled from stack.env
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /DATA/AppData/servarr/qbittorrent:/config
      - ${DOWNLOAD_FOLDER}:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  # # See the 'qBittorrent Stalls with VPN Timeout' section for more information.
  deunhealth:
    container_name: deunhealth
    image: qmcgaw/deunhealth
    network_mode: none
    environment:
      LOG_LEVEL: info
      HEALTH_SERVER_ADDRESS: 127.0.0.1:9999
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nzbget:
    container_name: nzbget
    image: lscr.io/linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/servarr/nzbget:/config
      - ${DOWNLOAD_FOLDER}:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/servarr/prowlarr:/config
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/servarr/radarr:/config
      - ${DATA_FOLDER}:/data/media:rslave
      - ${DOWNLOAD_FOLDER}:/downloads
      - /mnt:/mnt:rslave
      - /media:/media:rslave
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/servarr/sonarr:/config
      - ${DATA_FOLDER}:/data/media:rslave
      - ${DOWNLOAD_FOLDER}:/downloads
      - /mnt:/mnt:rslave
      - /media:/media:rslave
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/servarr/lidarr:/config
      - ${DATA_FOLDER}:/data/media:rslave
      - ${DOWNLOAD_FOLDER}:/downloads
      - /mnt:/mnt:rslave
      - /media:/media:rslave
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/servarr/bazarr:/config
      - ${DATA_FOLDER}:/data/media:rslave
      - ${DOWNLOAD_FOLDER}:/downloads
      - /mnt:/mnt:rslave
      - /media:/media:rslave
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  mylar:
    container_name: mylar
    image: lscr.io/linuxserver/mylar3:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/servarr/mylar:/config
      - ${DATA_FOLDER}:/data/media:rslave
      - ${DOWNLOAD_FOLDER}:/downloads
      - /mnt:/mnt:rslave
      - /media:/media:rslave
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/servarr/mylar:/config
      - ${DATA_FOLDER}:/data/media:rslave
      - ${DOWNLOAD_FOLDER}:/downloads
      - /mnt:/mnt:rslave
      - /media:/media:rslave
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

networks:
  servarrnetwork:
    name: servarrnetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.39.0.0/24
