name: headscale
services:
  headscale:
    container_name: headscale
    image: ghcr.io/juanfont/headscale:latest
    restart: unless-stopped
    hostname: headscale
    command: serve
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.headscale.loadbalancer.server.port: "8080"

      traefik.http.routers.headscale-duckdns-local.rule: Host(`headscale.lucarotto-local.duckdns.org`)
      traefik.http.routers.headscale-duckdns-local.entrypoints: https
      traefik.http.routers.headscale-duckdns-local.tls: true
      traefik.http.routers.headscale-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.headscale-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.headscale-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.headscale-local.rule: Host(`headscale.l.lucarotto.it`)
      traefik.http.routers.headscale-local.entrypoints: http

      traefik.http.routers.headscale-internet.rule: Host(`headscale.lucarotto.it`)
      traefik.http.routers.headscale-internet.entrypoints: https-internet
      traefik.http.routers.headscale-internet.tls: true
      traefik.http.routers.headscale-internet.tls.certresolver: lucarotto-http
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports: []
      # Disabled in favor of Traefik routing
      # - 8055:8080/tcp # STUN server
      # - 9055:9090/tcp # Metrics service
    volumes:
      - /DATA/AppData/headscale/data:/var/lib/headscale
      - /DATA/AppData/headscale/config:/etc/headscale
      - /DATA/AppData/headscale/run:/var/run/headscale
    dns:
      - 192.168.5.201

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    hostname: headscale-ui
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.headscale-ui.loadbalancer.server.port: "8080"

      traefik.http.routers.headscale-ui-duckdns-local.rule: Host(`headscale.lucarotto-local.duckdns.org`) && PathPrefix(`/web`)
      traefik.http.routers.headscale-ui-duckdns-local.entrypoints: https
      traefik.http.routers.headscale-ui-duckdns-local.tls: true
      traefik.http.routers.headscale-ui-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.headscale-ui-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.headscale-ui-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.headscale-ui-local.rule: Host(`headscale.l.lucarotto.it`) && PathPrefix(`/web`)
      traefik.http.routers.headscale-ui-local.entrypoints: http
    depends_on:
      headscale:
        condition: service_started
        required: true
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports: []
      # Disabled in favor of Traefik routing
      # - 5080:8080/tcp # HTTP
      # - 5443:8443/tcp # HTTPS
    dns:
      - 192.168.5.201

  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:latest
    restart: unless-stopped
    hostname: headplane
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.headplane.loadbalancer.server.port: "3000"

      traefik.http.routers.headplane-duckdns-local.rule: Host(`headscale.lucarotto-local.duckdns.org`) && PathPrefix(`/admin`)
      traefik.http.routers.headplane-duckdns-local.entrypoints: https
      traefik.http.routers.headplane-duckdns-local.tls: true
      traefik.http.routers.headplane-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.headplane-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.headplane-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.headplane-local.rule: Host(`headscale.l.lucarotto.it`) && PathPrefix(`/admin`)
      traefik.http.routers.headplane-local.entrypoints: http
    depends_on:
      headscale:
        condition: service_started
        required: true
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports: []
      # Disabled in favor of Traefik routing
      # - '3000:3000'
    volumes:
      - /DATA/AppData/headplane/config:/etc/headplane
      - /DATA/AppData/headplane/data:/var/lib/headplane
    dns:
      - 192.168.5.201

networks:
  traefik:
    external: true
