name: headscale
services:
  headscale:
    container_name: headscale
    image: ghcr.io/juanfont/headscale:latest
    restart: unless-stopped
    hostname: headscale
    command: serve
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.headscale.loadbalancer.server.port: "8080"

      traefik.http.routers.headscale-duckdns-local.rule: Host(`headscale.lucarotto-local.duckdns.org`)
      traefik.http.routers.headscale-duckdns-local.entrypoints: https
      traefik.http.routers.headscale-duckdns-local.tls: true
      traefik.http.routers.headscale-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.headscale-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.headscale-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.headscale-local.rule: Host(`headscale.l.lucarotto.it`)
      traefik.http.routers.headscale-local.entrypoints: http
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8055:8080
      # - 9055:9090 # Metrics service
    volumes:
      - /DATA/AppData/headscale/data:/var/lib/headscale
      - /DATA/AppData/headscale/config:/etc/headscale
      - /DATA/AppData/headscale/run:/var/run/headscale
    dns:
      - 172.18.0.100

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    hostname: headscale-ui
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.headscale-ui.loadbalancer.server.port: "8080"

      traefik.http.routers.headscale-ui-duckdns-local.rule: Host(`headscale.lucarotto-local.duckdns.org`) && PathPrefix(`/web`)
      traefik.http.routers.headscale-ui-duckdns-local.entrypoints: https
      traefik.http.routers.headscale-ui-duckdns-local.tls: true
      traefik.http.routers.headscale-ui-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.headscale-ui-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.headscale-ui-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.headscale-ui-local.rule: Host(`headscale.l.lucarotto.it`) && PathPrefix(`/web`)
      traefik.http.routers.headscale-ui-local.entrypoints: http
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
    # - 5443:8443 # HTTPS
    - 5080:8080 # HTTP
    dns:
      - 172.18.0.100

networks:
  traefik:
    external: true
