name: memos
services:
  memos:
    container_name: memos
    image: neosmemo/memos:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: memos
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 5230:5230/tcp
    volumes:
      - /DATA/AppData/memos/memos:/var/opt/memos
