name: memos
services:
  memos:
    container_name: memos
    image: neosmemo/memos:latest
    restart: unless-stopped
    hostname: memos
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.memos.loadbalancer.server.port: "5230"

      traefik.http.routers.memos-duckdns-local.rule: Host(`memos.lucarotto-local.duckdns.org`)
      traefik.http.routers.memos-duckdns-local.entrypoints: https
      traefik.http.routers.memos-duckdns-local.tls: true
      traefik.http.routers.memos-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.memos-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.memos-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.memos-local.rule: Host(`memos.l.lucarotto.it`)
      traefik.http.routers.memos-local.entrypoints: http
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports: []
      # Disabled in favor of Traefik routing
      # - 5230:5230/tcp
    volumes:
      - /DATA/AppData/memos/memos:/var/opt/memos
    dns:
      - 192.168.5.201

networks:
  traefik:
    external: true
