name: metube
services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: metube
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8081:8081/tcp
    volumes:
      - /DATA/Downloads/metube:/downloads
