name: adguard-home
services:
  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: adguard-home
    command:
      - --no-check-update
      - -c
      - /opt/adguardhome/conf/AdGuardHome.yaml
      - -w
      - /opt/adguardhome/work
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp

      # DHCP
      # - 67:68/udp
      # - 68:68/tcp
      # - 68:68/udp

      # Admin Panel
      - 3002:80/tcp
      - 3003:443/tcp
      - 3003:443/udp

      # DNS Over TLS
      - 853:853/tcp
    volumes:
      - /DATA/AppData/adguard-home/conf:/opt/adguardhome/conf
      - /DATA/AppData/adguard-home/work:/opt/adguardhome/work
