name: adguard-home
services:
  adguard-home:
    command:
      - --no-check-update
      - -c
      - /opt/adguardhome/conf/AdGuardHome.yaml
      - -w
      - /opt/adguardhome/work
    environment:
      OPENAI_API_KEY: sk-xxxxxx
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    image: adguard/adguardhome:latest
    network_mode: bridge
    ports:
      # DNX
      - target: 53
        published: "53"
        protocol: tcp
      - target: 53
        published: "53"
        protocol: udp

        # DHCP
      - target: 67
        published: "68"
        protocol: udp
      - target: 68
        published: "68"
        protocol: tcp
      - target: 68
        published: "68"
        protocol: udp

        # Admin Panel
      - target: 80
        published: "3002"
        protocol: tcp
      - target: 443
        published: "3003"
        protocol: tcp
      - target: 443
        published: "3003"
        protocol: udp

        # DNS Over TLS
      - target: 853
        published: "853"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/adguard-home/conf
        target: /opt/adguardhome/conf
      - type: bind
        source: /DATA/AppData/adguard-home/work
        target: /opt/adguardhome/work
