name: adguard-home
services:
  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome:latest
    restart: unless-stopped
    hostname: adguard-home
    command:
      - --no-check-update
      - -c
      - /opt/adguardhome/conf/AdGuardHome.yaml
      - -w
      - /opt/adguardhome/work
    networks:
      traefik:
        ipv4_address: 172.18.0.100
    labels:
      traefik.enable: true
      traefik.http.services.adguard.loadbalancer.server.port: "80"

      traefik.http.routers.adguard-duckdns-local.rule: Host(`adguard.lucarotto-local.duckdns.org`)
      traefik.http.routers.adguard-duckdns-local.entrypoints: https
      traefik.http.routers.adguard-duckdns-local.tls: true
      traefik.http.routers.adguard-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.adguard-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.adguard-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.adguard-local.rule: Host(`adguard.l.lucarotto.it`)
      traefik.http.routers.adguard-local.entrypoints: http
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp

      # DHCP
      # - 67:68/udp
      # - 68:68/tcp
      # - 68:68/udp

      # Admin Panel
      # Disabled in favor of Traefik routing
      # - 3002:80/tcp # HTTP Admin Panel
      # - 3003:443/tcp # HTTPS Admin Panel

      # DNS Over TLS
      - 853:853/tcp
    volumes:
      - /DATA/AppData/adguard-home/conf:/opt/adguardhome/conf
      - /DATA/AppData/adguard-home/work:/opt/adguardhome/work

networks:
  traefik:
    external: true
