name: tailscale
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: tailscale
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: minipc
      TS_EXTRA_ARGS: --advertise-routes=192.168.5.0/24 --advertise-exit-node --webclient
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 5252:5252/tcp
    volumes:
      - /DATA/AppData/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false
