name: tailscale
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: tailscale
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.tailscale.loadbalancer.server.port: "5252"

      traefik.http.routers.tailscale-duckdns-local.rule: Host(`tailscale.lucarotto-local.duckdns.org`)
      traefik.http.routers.tailscale-duckdns-local.entrypoints: https
      traefik.http.routers.tailscale-duckdns-local.tls: true
      traefik.http.routers.tailscale-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.tailscale-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.tailscale-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.tailscale-local.rule: Host(`tailscale.l.lucarotto.it`)
      traefik.http.routers.tailscale-local.entrypoints: http
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: minipc
      TS_EXTRA_ARGS: --advertise-routes=192.168.5.201/32 --advertise-exit-node --login-server=https://headscale.lucarotto.it --accept-routes
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports: []
      # Disabled in favor of Traefik routing
      # - 5252:5252/tcp
    volumes:
      - /DATA/AppData/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false
    dns:
      - 172.18.0.100

networks:
  traefik:
    external: true
