name: code-server
services:
  code-server:
    container_name: code-server
    image: linuxserver/code-server:4.100.2
    network_mode: bridge
    restart: unless-stopped
    hostname: code-server
    environment:
      PGID: "1000"
      PUID: "1000"
      DEFAULT_WORKSPACE: /DATA/AppData
      TZ: Etc/UTC
    ports:
      - 8087:8443/tcp
    volumes:
      - /DATA/AppData/code-server/config:/config
      - /DATA/AppData/code-server/projects:/projects
      - /DATA:/DATA
