name: code-server
services:
  code-server:
    container_name: code-server
    image: linuxserver/code-server:4.100.2
    network_mode: bridge
    restart: unless-stopped
    hostname: code-server
    environment:
      PGID: "1000"
      PUID: "1000"
      DEFAULT_WORKSPACE: /DATA/AppData
      TZ: Etc/UTC
    ports:
      - target: 8443
        published: "8087"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/code-server/config
        target: /config
      - type: bind
        source: /DATA/AppData/code-server/projects
        target: /projects
      - type: bind
        source: /DATA
        target: /DATA
