name: navidrome
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: navidrome
    environment:
      ND_BASEURL: ""
      ND_LOGLEVEL: info
      ND_SCANSCHEDULE: 1h
      ND_SESSIONTIMEOUT: 24h
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 4533:4533/tcp
    volumes:
      - /DATA/AppData/navidrome/data:/data
      - /DATA/Media/Music:/music
