name: navidrome
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    hostname: navidrome
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.navidrome.loadbalancer.server.port: "4533"

      traefik.http.routers.navidrome-duckdns-local.rule: Host(`navidrome.lucarotto-local.duckdns.org`)
      traefik.http.routers.navidrome-duckdns-local.entrypoints: https
      traefik.http.routers.navidrome-duckdns-local.tls: true
      traefik.http.routers.navidrome-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.navidrome-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.navidrome-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.navidrome-local.rule: Host(`navidrome.l.lucarotto.it`)
      traefik.http.routers.navidrome-local.entrypoints: http
    environment:
      ND_BASEURL: ""
      ND_LOGLEVEL: info
      ND_SCANSCHEDULE: 1h
      ND_SESSIONTIMEOUT: 24h
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 4533:4533/tcp
    volumes:
      - /DATA/AppData/navidrome/data:/data
      - /DATA/Media/Music:/music

networks:
  traefik:
    external: true
