name: dozzle
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    hostname: dozzle
    networks:
      - traefik
    labels:
      traefik.enable: true

      traefik.http.routers.dozzle-duckdns-local.rule: Host(`dozzle.lucarotto-local.duckdns.org`)
      traefik.http.routers.dozzle-duckdns-local.entrypoints: https
      traefik.http.routers.dozzle-duckdns-local.tls: true
      traefik.http.routers.dozzle-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.dozzle-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.dozzle-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.dozzle-local.rule: Host(`dozzle.l.lucarotto.it`)
      traefik.http.routers.dozzle-local.entrypoints: http
    environment:
      DOZZLE_ENABLE_ACTIONS: "true"
      DOZZLE_ENABLE_SHELL: "true"
      DOZZLE_NO_ANALYTICS: "true"
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8041:8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/dozzle:/data

networks:
  traefik:
    external: true
