name: traefik
services:
  traefik:
    container_name: traefik
    image: traefik:v3
    restart: unless-stopped
    hostname: traefik
    networks:
      - traefik
      - servarrnetwork
    labels:
      traefik.enable: true
      traefik.http.services.traefik.loadbalancer.server.port: "8080"

      traefik.http.routers.traefik-duckdns-local.rule: Host(`traefik.lucarotto-local.duckdns.org`)
      traefik.http.routers.traefik-duckdns-local.entrypoints: https
      traefik.http.routers.traefik-duckdns-local.tls: true
      traefik.http.routers.traefik-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.traefik-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.traefik-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.traefik-local.rule: Host(`traefik.l.lucarotto.it`)
      traefik.http.routers.traefik-local.entrypoints: http
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports:
      # Local reverse proxy
      - 80:80/tcp
      - 80:80/udp
      - 443:443/tcp
      - 443:443/udp
      # Internet reverse proxy
      - 2280:2280/tcp
      - 2280:2280/udp
      - 2443:2443/tcp
      - 2443:2443/udp
      # Traefik Dashboard
      # - 1180:8080/tcp # Disabled in favor of Traefik routing
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/traefik/config:/etc/traefik:rslave
      - /DATA/AppData/traefik/certs:/var/traefik/certs:rw
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false
    dns:
      - 172.18.0.100

networks:
  traefik:
    name: traefik
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
  servarrnetwork:
    external: true