name: traefik
services:
  traefik:
    container_name: traefik
    image: traefik:v3
    networks:
      - traefik
    restart: unless-stopped
    hostname: traefik
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 3380:80/tcp
      - 3380:80/udp
      - 3443:443/tcp
      - 3443:443/udp
      - 1180:8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/traefik/config:/etc/traefik:ro
      - /DATA/AppData/traefik/certs:/var/traefik/certs:rw
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  traefik:
    name: traefik
    driver: bridge
