name: mealie
services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: mealie
    ports:
      - 9000:9925/tcp
    environment:
      ALLOW_SIGNUP: "true"
      BASE_URL: https://mealie.lucarotto.duckdns.org
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /DATA/AppData/mealie:/app/data/
