name: filebrowser
services:
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: jellyfin
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
      FB_BASEURL: /
    ports:
      - 3333:8080
    volumes:
      - /DATA/AppData/filebrowser/config:/config
      - /DATA:/DATA
      - /media:/media
      - /mnt:/mnt
