name: cup
services:
  cup:
    container_name: cup
    image: ghcr.io/sergi0g/cup:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: cup
    command:
      - serve
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8001:8000/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/cup:/config
