name: cup
services:
  cup:
    container_name: cup
    image: ghcr.io/sergi0g/cup:latest
    restart: unless-stopped
    hostname: cup
    command:
      - serve
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.cup.loadbalancer.server.port: "8000"

      traefik.http.routers.cup-duckdns-local.rule: Host(`cup.lucarotto-local.duckdns.org`)
      traefik.http.routers.cup-duckdns-local.entrypoints: https
      traefik.http.routers.cup-duckdns-local.tls: true
      traefik.http.routers.cup-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.cup-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.cup-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.cup-local.rule: Host(`cup.l.lucarotto.it`)
      traefik.http.routers.cup-local.entrypoints: http
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports: []
      # Disabled in favor of Traefik routing
      # - 8001:8000/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /DATA/AppData/cup:/config
    dns:
      - 192.168.5.201

networks:
  traefik:
    external: true
