name: portainer
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.30.1
    network_mode: bridge
    restart: unless-stopped
    hostname: portainer
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8000:8000/tcp
      - 9000:9000/tcp
      - 9443:9443/tcp
    volumes:
      - /DATA/AppData/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
