name: jellyseerr
services:
  app:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: Jellyseerr
    environment:
      LOG_LEVEL: info
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 5055:5055/tcp
    volumes:
      - /DATA/AppData/jellyseerr/config:/app/config
