name: audiobookshelf
services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: audiobookshelf
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 80:1080/tcp
    volumes:
      - /mnt/data/Media/Audiobooks:/audiobooks
      - /mnt/data/Media/Podcasts:/podcasts
      - /DATA/AppData/audiobookshelf/data/config:/config
      - /DATA/AppData/audiobookshelf/data/metadata:/metadata
