name: manga
services:
  suwayomi:
    container_name: suwayomi
    image: ghcr.io/suwayomi/tachidesk:latest
    restart: unless-stopped
    hostname: suwayomi
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.suwayomi.loadbalancer.server.port: "4567"

      traefik.http.routers.suwayomi-duckdns-local.rule: Host(`suwayomi.lucarotto-local.duckdns.org`) || Host(`manga.lucarotto-local.duckdns.org`)
      traefik.http.routers.suwayomi-duckdns-local.entrypoints: https
      traefik.http.routers.suwayomi-duckdns-local.tls: true
      traefik.http.routers.suwayomi-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.suwayomi-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.suwayomi-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.suwayomi-local.rule: Host(`suwayomi.l.lucarotto.it`) || Host(`manga.l.lucarotto.it`)
      traefik.http.routers.suwayomi-local.entrypoints: http
    environment:
      BIND_IP: 0.0.0.0
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports: []
      # Disabled in favor of Traefik routing
      # - 4567:4567/tcp
    volumes:
      - /DATA/Downloads/manga:/home/suwayomi/.local/share/Tachidesk/downloads/mangas
      - /DATA/AppData/suwayomi/backups:/home/suwayomi/.local/share/Tachidesk/backups
      - suwayomi:/home/suwayomi/.local/share/Tachidesk
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 172.18.0.100

  komga:
    container_name: komga
    image: gotson/komga:latest
    restart: unless-stopped
    hostname: komga
    networks:
      - traefik
    volumes:
      - /DATA/AppData/komga/config:/config
      - /DATA/AppData/komga/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 25600:25600
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC

  kavita:
    container_name: kavita
    image: jvmilazz0/kavita:latest
    restart: unless-stopped
    hostname: kavita
    networks:
      - traefik
    volumes:
      - /DATA/AppData/kavita/config:/kavita/config
      - /DATA/AppData/kavita/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC

volumes:
  suwayomi: {}

networks:
  traefik:
    external: true
