name: spotizerr

services:
  spotizerr:
    container_name: spotizerr
    image: cooldockerizer93/spotizerr
    restart: unless-stopped
    hostname: spotizerr
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.spotizerr.loadbalancer.server.port: "7171"

      traefik.http.routers.spotizerr-duckdns-local.rule: Host(`spotizerr.lucarotto-local.duckdns.org`)
      traefik.http.routers.spotizerr-duckdns-local.entrypoints: https
      traefik.http.routers.spotizerr-duckdns-local.tls: true
      traefik.http.routers.spotizerr-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.spotizerr-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.spotizerr-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.spotizerr-local.rule: Host(`spotizerr.l.lucarotto.it`)
      traefik.http.routers.spotizerr-local.entrypoints: http
    environment:
      UMASK: 022 # Optional: Sets the default file permissions for newly created files within the container.
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}  # Optional, Redis AUTH password. Leave empty if not using authentication
      REDIS_URL: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      REDIS_BACKEND: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      EXPLICIT_FILTER: "false" # Set to true to filter out explicit content
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports: []
      # Disabled in favor of Traefik routing
      # - 7171:7171
    volumes:
      - /DATA/AppData/spotizer/data:/app/data
      - /DATA/Downloads/spotizer:/app/downloads  # <-- Change this for your music library dir
      # - /DATA/AppData/spotizer/logs:/app/logs  # <-- Volume for persistent logs
      - /mnt:/mnt:rslave
      - /media:/media:rslave
    depends_on:
      - spotizerr-redis
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false
    dns:
      - 172.18.0.100

  spotizerr-redis:
    container_name: spotizerr-redis
    image: redis:alpine
    restart: unless-stopped
    hostname: spotizerr-redis
    networks:
      - traefik
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - /DATA/AppData/spotizer/redis:/data
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false

networks:
  traefik:
    external: true

