name: duckdns
services:
  duckdns:
    container_name: duckdns
    image: lscr.io/linuxserver/duckdns:latest
    network_mode: host
    restart: unless-stopped
    hostname: duckdns
    environment:
      SUBDOMAINS: lucarotto
      TOKEN: ${TOKEN}
      LOG_FILE: "false"
      UPDATE_IP: ipv6
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    volumes:
      - /DATA/AppData/duckdns:/config
    env_file:
      - path: .env
        required: true
      - path: ../../stack.env
        required: false
