name: syncthing
services:
  syncthing-local:
    container_name: syncthing-local
    image: linuxserver/syncthing:latest
    restart: unless-stopped
    hostname: syncthing-local
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.syncthing-local.loadbalancer.server.port: "80"

      traefik.http.routers.syncthing-local-duckdns-local.rule: Host(`syncthing-local.lucarotto-local.duckdns.org`)
      traefik.http.routers.syncthing-local-duckdns-local.entrypoints: https
      traefik.http.routers.syncthing-local-duckdns-local.tls: true
      traefik.http.routers.syncthing-local-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.syncthing-local-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.syncthing-local-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.syncthing-local-local.rule: Host(`syncthing-local.l.lucarotto.it`)
      traefik.http.routers.syncthing-local-local.entrypoints: http
    environment:
      HOME: /config
      LSIO_FIRST_PARTY: "true"
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PS1: $$$$$$$$(whoami)@$$$$$$$$(hostname):$$$$$$$$(pwd)\$$$$$$$$
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: "0"
      S6_STAGE2_HOOK: /docker-mods
      S6_VERBOSITY: "1"
      TERM: xterm
      VIRTUAL_ENV: /lsiopy
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 8385:8384/tcp
      - 22001:22000/tcp
      - 22001:22000/udp
      - 21028:21027/udp
    volumes:
      - /DATA/AppData/syncthing-local/config:/config
      - /DATA:/DATA
      - /mnt:/mnt:rslave
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT

  syncthing-remote:
    container_name: syncthing-remote
    image: linuxserver/syncthing:latest
    restart: unless-stopped
    hostname: syncthing-remote
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.syncthing-remote.loadbalancer.server.port: "80"

      traefik.http.routers.syncthing-remote-duckdns-local.rule: Host(`syncthing-remote.lucarotto-local.duckdns.org`)
      traefik.http.routers.syncthing-remote-duckdns-local.entrypoints: https
      traefik.http.routers.syncthing-remote-duckdns-local.tls: true
      traefik.http.routers.syncthing-remote-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.syncthing-remote-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.syncthing-remote-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.syncthing-remote-local.rule: Host(`syncthing-remote.l.lucarotto.it`)
      traefik.http.routers.syncthing-remote-local.entrypoints: http
    environment:
      HOME: /config
      LSIO_FIRST_PARTY: "true"
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PS1: $$$$(whoami)@$$$$(hostname):$$$$(pwd)\$$$$
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: "0"
      S6_STAGE2_HOOK: /docker-mods
      S6_VERBOSITY: "1"
      TERM: xterm
      VIRTUAL_ENV: /lsiopy
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    ports:
      - 8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - /DATA/AppData/syncthing-remote/config:/config
      - /mnt:/mnt:rslave
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT

networks:
  traefik:
    external: true
