name: syncthing
services:
  syncthing-local:
    container_name: syncthing-local
    image: linuxserver/syncthing:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: syncthing-local
    environment:
      HOME: /config
      LSIO_FIRST_PARTY: "true"
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PS1: $$$$$$$$(whoami)@$$$$$$$$(hostname):$$$$$$$$(pwd)\$$$$$$$$
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: "0"
      S6_STAGE2_HOOK: /docker-mods
      S6_VERBOSITY: "1"
      TERM: xterm
      VIRTUAL_ENV: /lsiopy
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 22000:22001/udp
      - 8384:8385/tcp
      - 21027:21028/udp
      - 22000:22001/tcp
    volumes:
      - /DATA/AppData/syncthing-local/config:/config
      - /DATA:/DATA
      - /mnt:/mnt:rslave
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT

  syncthing-remote:
    container_name: syncthing-remote
    image: linuxserver/syncthing:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: syncthing-remote
    environment:
      HOME: /config
      LSIO_FIRST_PARTY: "true"
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PS1: $$$$(whoami)@$$$$(hostname):$$$$(pwd)\$$$$
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: "0"
      S6_STAGE2_HOOK: /docker-mods
      S6_VERBOSITY: "1"
      TERM: xterm
      VIRTUAL_ENV: /lsiopy
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    ports:
      - 21027:21027/udp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 8384:8384/tcp
    volumes:
      - /DATA/AppData/syncthing-remote/config:/config
      - /mnt:/mnt:rslave
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
