name: wg-easy
services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: wg-easy
    environment:
      PASSWORD_HASH: $$2a$$12$$y0MLjQ9cOBNtCyq5.RMlju3XCFpBEr9KuC.Y9fqie5UYMrTPHuiCu
      WG_DEFAULT_DNS: 192.168.5.201
      WG_HOST: lucarotto.duckdns.org
      WG_PORT: "51820"
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    volumes:
      - /DATA/AppData/wg-easy/wireguard/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"
