name: wg-easy
services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:latest
    network_mode: bridge
    restart: unless-stopped
    hostname: wg-easy
    environment:
      PASSWORD_HASH: $$2a$$12$$y0MLjQ9cOBNtCyq5.RMlju3XCFpBEr9KuC.Y9fqie5UYMrTPHuiCu
      WG_DEFAULT_DNS: 192.168.1.201
      WG_HOST: lucarotto.duckdns.org
      WG_PORT: "51820"
    ports:
      - target: 51820
        published: "51820"
        protocol: udp
      - target: 51821
        published: "51821"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wg-easy/wireguard
        target: /etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"
