name: tinyproxy
services:
  tinyproxy:
    container_name: tinyproxy
    image: ajoergensen/tinyproxy:latest
    restart: unless-stopped
    network_mode: bridge
    hostname: tinyproxy
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports:
      - 8888:8888/tcp
    volumes:
      - /DATA/AppData/tinyproxy:/etc/tinyproxy
