name: telegram-files
services:
  telegram-files:
    container_name: telegram-files
    image: ghcr.io/jarvis2f/telegram-files:latest
    restart: unless-stopped
    hostname: telegram-files
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.telegram-files.loadbalancer.server.port: "80"

      traefik.http.routers.telegram-files-duckdns-local.rule: Host(`telegram-files.lucarotto-local.duckdns.org`)
      traefik.http.routers.telegram-files-duckdns-local.entrypoints: https
      traefik.http.routers.telegram-files-duckdns-local.tls: true
      traefik.http.routers.telegram-files-duckdns-local.tls.certresolver: duckdns
      traefik.http.routers.telegram-files-duckdns-local.tls.domains[0].main: lucarotto-local.duckdns.org
      traefik.http.routers.telegram-files-duckdns-local.tls.domains[0].sans: "*.lucarotto-local.duckdns.org"

      traefik.http.routers.telegram-files-local.rule: Host(`telegram-files.l.lucarotto.it`)
      traefik.http.routers.telegram-files-local.entrypoints: http
    environment:
      APP_ENV: prod
      APP_ROOT: /app/data
      TELEGRAM_API_HASH: bd3351253ad4376ddc9f3214589ebf93
      TELEGRAM_API_ID: "79100"
      TELEGRAM_LOG_LEVEL: "2"
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Paris
    ports: []
      # Disabled in favor of Traefik routing
      # - 7745:80/tcp
    volumes:
      - /DATA/AppData/telegram-files:/app/data
    dns:
      - 172.18.0.100

networks:
  traefik:
    external: true
